[directory]
truncation_length = 3
truncate_to_repo = false
style = "bold blue"

[git_branch]
symbol = ' '
style = 'bold purple'

[cmd_duration]
min_time = 10
show_milliseconds = true
format = 'took [$duration](bold yellow) '

[time]
disabled = false
format = '[$time]($style)'
